roasts = [
"You play Tic Tac Toe like a potato.",
"I've seen better moves from a broken robot.",
"Are you trying to lose on purpose?",
"You couldn't win a game against yourself.",
"I've seen cats play better.",
"You make losing an art form.",
"Are you playing Tic Tac Toe or doodling?",
"You’d lose against a mirror.",
"The Xs and Os are ashamed.",
"I've seen better moves in Jenga.",
"Even a coin flip is more strategic.",
"Your moves make my brain hurt.",
"Congrats, you invented 'Tic Tac Lose.'",
"Even a goldfish would beat you.",
"You play Tic Tac Toe like it's chess... badly.",
"Are you trying to play Connect Four?",
"You missed the tutorial, didn’t you?",
"Your strategy is non-existent.",
"You’re single-handedly making Tic Tac Toe boring.",
"Did you close your eyes before each move?",
"Even your shadow wins.",
"Did you forget how the game works?",
"You’d lose in a game with one square.",
"You’ve perfected the art of losing.",
"Your strategy is a mystery… even to you.",
"Even toddlers could beat you.",
"You play like the board is invisible.",
"You missed your calling as a professional loser.",
"The only X you know is wrong.",
"It’s called Tic Tac Toe, not Tic Tac Lose.",
"Even the board feels sorry for you.",
"You must really enjoy losing.",
"Your next move? Don’t.",
"Your best move is quitting.",
"You’d lose against a beginner’s guide.",
"Your moves are a cry for help.",
"I've seen tumbleweeds with more action.",
"Your game plan is a blank page.",
"You’d lose to a random number generator.",
"Even the board is confused.",
"You’re making a circle, not progress.",
"Your next move? A nap.",
"Are you playing Tic Tac Nope?",
"Even the tutorial gave up on you.",
"I've seen bricks think faster.",
"You’re the king of ties… and losses.",
"Are you allergic to winning?",
"You’d lose in a game with one move.",
"Is this your first time seeing a Tic Tac Toe board?",
"I didn’t know losing could be so consistent.",
"Are you playing Tic Tac Uh-Oh?",
"You’re making losing look effortless.",
"Your strategy? Waiting to lose.",
"I've seen plants think faster.",
"Even the board feels bad for you.",
"You must really like the 'L' shape.",
"Your Xs are just excuses.",
"You put the 'tactic' in tragic.",
"Do you always choose the worst square?",
"Your best move was leaving the game.",
"You make the O’s cry.",
"You’re one move away from losing… always.",
"Your strategy is just hoping.",
"Even a pencil has better marks.",
"You’ve mastered the art of second place.",
"Is there a wrong way to play? You found it.",
"You're so bad, even the AI pities you.",
"Every square you choose is a mistake.",
"Do you enjoy watching yourself lose?",
"The game’s over before you start.",
"You’ve got Tic Tac Woe written all over you.",
"Your moves are a disaster.",
"You’re on a losing streak… forever.",
"Even a dice would make better choices.",
"You’re giving free wins out here.",
"I've seen glaciers move faster.",
"Are you playing Tic Tac Oops?",
"Your strategy is one step closer to losing.",
"You’ve mastered the art of giving up.",
"You’d lose to an empty board.",
"Even ghosts make better moves.",
"Your best strategy is surrender.",
"Do you play Tic Tac Toe or just toe?",
"You’re a Tic Tac Nope master.",
"I didn’t know losing was a strategy.",
"Your next move is already wrong.",
"Is there a tutorial for losing? You wrote it.",
"Every time you move, a strategy cries.",
"You’re a Tic Tac Wreck.",
"I’ve seen better moves in checkers.",
"You lose so much, even the board feels bad.",
"You’re aiming for the wrong spots, aren’t you?",
"You’re two steps behind… in a one-step game.",
"Your O's are just holes in your strategy.",
"You’re not even playing, are you?",
"You’ve got a 100% lose rate.",
"Did you misplace your brain in this game?",
"Your best move was not playing.",
"You could turn a win into a loss.",
"Even luck won't help you win.",
"You're the reason Tic-Tac-Toe boards come with an eraser.",
"You could lose a Tic-Tac-Toe game against a rock.",
"If brains were Tic-Tac-Toe moves, you'd still be playing checkers.",
"Your Tic-Tac-Toe strategy is as solid as a wet tissue.",
"You lose to the mirror and still ask for a rematch.",
"If losing Tic-Tac-Toe was an Olympic sport, you’d still come in second.",
"You play Tic-Tac-Toe like you think 'X' marks the spot in Minesweeper.",
"I’ve seen toddlers win with more grace than you lose.",
"Your Tic-Tac-Toe skills make toddlers look like grandmasters.",
"If you played a game of Tic-Tac-Toe with death, the Grim Reaper would get bored and quit.",
"You make 'three in a row' sound impossible.",
"You could lose Tic-Tac-Toe with four chances in a row.",
"Playing Tic-Tac-Toe against you is like fighting an unarmed man.",
"I’d tell you to stop playing, but watching you lose is pure comedy.",
"If Tic-Tac-Toe had a tutorial, you'd still fail.",
"Watching you play is like watching someone drown in a puddle.",
"You're the only person who makes tying in Tic-Tac-Toe look difficult.",
"A game of Tic-Tac-Toe with you ends in confusion, shame, and regret.",
"Even a blindfolded monkey could outplay you.",
"You could lose Tic-Tac-Toe to a potato with Wi-Fi.",
"Your strategy is about as effective as screaming at a brick wall.",
"I’d call your Tic-Tac-Toe skills tragic, but that’s an insult to tragedies.",
"If bad Tic-Tac-Toe skills were a crime, you’d be on death row.",
"You’re the reason Tic-Tac-Toe isn’t considered a 'real' game.",
"You’ve turned Tic-Tac-Toe into a new form of self-torture.",
"Even with the cheat sheet, you’d still blow it.",
"You're like the Tic-Tac-Toe version of Murphy’s Law – if it can go wrong, it will.",
"Your best Tic-Tac-Toe move is rage quitting.",
"Losing to you feels like a crime against intelligence.",
"If you were any worse, you’d invent a fourth mark and still lose.",
"They say Tic-Tac-Toe is a game of strategy – you’re just here for the vibes.",
"You couldn’t outwit a fish in this game.",
"Playing against you feels like charity work.",
"You make your opponents feel like champions – purely by comparison.",
"It’s almost like you think Tic-Tac-Toe is a slot machine.",
"You could lose with an extra move and a roadmap.",
"When you play, the board screams for mercy.",
"You don’t just lose; you find new ways to embarrass yourself.",
"I’d let you win, but I’m not sure that’s possible.",
"You could mess up a Tic-Tac-Toe game drawn in the sand.",
"Even when you win, you somehow lose the moral victory.",
"Your Tic-Tac-Toe game is a cry for help.",
"You play Tic-Tac-Toe like you're defusing a bomb with your feet.",
"If you had a time machine, you'd still lose on the second try.",
"The only X you're getting is on a failed Tic-Tac-Toe grid.",
"Watching you play feels like a slow-motion car crash.",
"Your Tic-Tac-Toe losses should be studied by psychologists.",
"You make losing an art form, but it's more abstract than skillful.",
"You could lose a Tic-Tac-Toe game drawn with crayons.",
"You play Tic-Tac-Toe like you’re paid to fail.",
"The 'X' stands for how many brain cells you’ve used.",
"Even if your opponent was asleep, you’d still lose.",
"You could lose to a wall – and I’m not sure which one’s smarter.",
"Your Tic-Tac-Toe strategy is 'hope my opponent feels sorry for me.'",
"You have the same win percentage as a vending machine in this game.",
"You’re the reason Tic-Tac-Toe comes with instructions – for adults.",
"I'd say 'get good,' but we both know that’s off the table.",
"Playing against you is like shooting fish in a barrel, if the barrel was a swimming pool.",
"If Tic-Tac-Toe had a difficulty setting, you’d still lose on easy mode.",
"You’re so bad at Tic-Tac-Toe that the board weeps before you even start.",
"If you tried to throw the game, it’d still look like an honest loss.",
"Your Tic-Tac-Toe tactics are as confusing as they are ineffective.",
"Losing a Tic-Tac-Toe game to you should come with a consolation prize.",
"You could lose with a one-square head start.",
"Even if you had an extra turn, you'd still mess it up.",
"You make a blank Tic-Tac-Toe board look intimidating.",
"Every game you play turns into an unsolvable puzzle.",
"If you got three X's in a row, I'd call a doctor.",
"Your best Tic-Tac-Toe move is closing the game.",
"You’re like a motivational poster for 'how not to play.'",
"You couldn't find a win in Tic-Tac-Toe if it came with a treasure map.",
"It’s almost like you're inventing new ways to lose.",
"Watching you play is like watching a horror movie—predictable and painful.",
"You have the tactical sense of a wet napkin.",
"You play Tic-Tac-Toe like you’re allergic to victory.",
"You turn a three-move game into an existential crisis.",
"Even in a dream, you’d still lose to your imagination.",
"Losing to you would be a paradox.",
"You couldn’t win a Tic-Tac-Toe game against a rolled-up newspaper.",
"If you had to survive by winning a Tic-Tac-Toe game, I’d start planning your funeral.",
"You’ve mastered the art of making the simplest game impossible.",
"Watching you play is a lesson in why some people should stick to coloring books.",
"You could lose with a board full of X's.",
"If there were a Hall of Shame for Tic-Tac-Toe, you’d have your own wing.",
"You make every game look like a crime scene – with you as the victim.",
"You play like the board’s out to get you.",
"Even the grid is disappointed in you.",
"Your opponent isn't playing Tic-Tac-Toe – they’re just watching you self-destruct.",
"The only thing worse than your game is your confidence in it.",
"If Tic-Tac-Toe were a survival skill, you’d be extinct.",
"You play like you’re actively trying to forget the rules.",
"I’d offer tips, but there’s no helping a lost cause.",
"You’re the Tic-Tac-Toe version of a Shakespearean tragedy.",
"A game with you is like a slow-motion train wreck – you see it coming, but you can't look away.",
"You’ve somehow managed to turn Tic-Tac-Toe into a game of humiliation.",
"Watching you play is like watching someone try to solve a Rubik's Cube with their elbows.",
"Your playstyle is more painful than stepping on a Lego.",
"You could lose to a glitch in a digital Tic-Tac-Toe game.",
"You’re so bad, the game stops being fun and becomes a philosophical debate on the nature of failure.",
"If losing was an art, you’d be Picasso."]